# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'InteractiveClusteringMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'NMapsMap', '3.10.1'

end
